name: Build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build
        run: |
          npm ci
          npm run pack-windows

      - name: Project information
        id: info
        uses: gregoranders/nodejs-project-info@v0.0.1

      - name: Upload
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/gamepad-logger ${{steps.info.outputs.version}}.exe
          asset_name: gamepad-logger.exe
          asset_content_type: application/octet-stream
